### ISSUE TITLE
Current page should be highlighted in the side menu

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/duckduckgo-help-pages#8]
Currently it's not possible to tell which page is currently selected in the left side menu (on desktop). A quick fix would be to add `font-weight: bold` to the CSS for the `.current` class.

**Comment by jbarrett** [comment]
I see bolding for the current page's link - probably a small tweak needed to existing functionality.

**Comment by tagawa** [comment]
Hmm, maybe it's my screen or browser (FF) then. The attached screenshot is what I see.

<img width="1013" alt="Screenshot 2019-03-22 at 10 30 29" src="https://user-images.githubusercontent.com/94173/54794980-36a75800-4c42-11e9-8c4b-6633f06f3112.png">

**Comment by moollaza** [comment]
Currently it darkens the colour and doesn't bold the font. I think the theme doesn't bold the font because then it would look like a category.

One though is to change the background color of the LI to make it really apparent:

<img width="1279" alt="Screen Shot 2019-03-22 at 2 30 57 PM" src="https://user-images.githubusercontent.com/873785/54845228-3beebc00-4caf-11e9-8e26-ac1ac58c76b7.png">

**Comment by tagawa** [comment]
Oh yes, that's much better 👍

**Comment by moollaza** [comment]
Fixed by #36
